/**
 * 模块地图 —— 全项目"要做哪些东西"的唯一清单。
 *
 * 新增一个功能模块 = 在这里加一条。status 决定界面上怎么显示：
 *   planned 只出现在地图里   stub 有接口没内容
 *   partial 部分能用          ready  能用
 *
 * 详细需求见 docs/功能蓝图.txt，blueprint 字段标了对应章节。
 */

export const MODULES = [
  // ---------- 写卡区 ----------
  {
    id: 'writing',
    area: 'writing',
    title: '写卡区',
    summary: '角色卡（含编辑器）、世界书、提示词（含 X 光机）、记忆（含向量）、卡内前端、写卡助手（含 MCP），都在这一块里',
    status: 'partial',
    web: { view: 'writing', icon: '✍️' },
    blueprint: '1',
    plan: [
      '一张卡一个工作台：列表 → 编辑器 → 世界书 → 提示词 → 记忆 → 向量',
      '写卡助手（Agent）：一句话生成草稿、按指令改写、体检、翻译',
      '技能（Skills）：可被助手调用的动作，也能单独跑一次',
      'MCP：把外部工具接进来当技能用',
      '提示词 X 光机：看到每轮真正发出去的东西',
    ],
  },
  {
    id: 'studio',
    area: 'writing',
    title: '工坊',
    summary: '写卡质检、建卡向导、世界书一行语法与递归地图、模块化 Markdown 卡、临场指令、采样器、套装、分支图',
    status: 'ready',
    web: { view: 'studio', icon: '🧪' },
    api: ['/api/studio'],
    dependsOn: ['cards', 'worldbook', 'prompts'],
    blueprint: '1',
    plan: [
      '写卡质检：七病灶配额、开场白九项硬检、八维评分、交付前闸门',
      '建卡向导：四元组选型 → 标签 + 骨架 + 作者的话模板',
      '世界书：一行语法批量粘贴、递归地图、条目体检',
      '模块化卡：Markdown 写卡 ↔ 卡数据双向转换',
      '临场指令：默认 / 角色 / 对话三层，位置、深度、角色、频率',
      '采样器：顺序可拖、每后端默认顺序、一键恢复、Neutralize',
      '套装：打包玩法配置，应用时可只应用其中一部分',
      '分支图：按内容哈希自动归类，不用手动建分支',
    ],
  },
  {
    id: 'agent',
    area: 'writing',
    title: '写卡助手',
    summary: 'Agent + 技能 + MCP，替你写卡、改卡、查资料',
    status: 'partial',
    nav: false,
    web: { view: 'agent', icon: '🤖' },
    api: ['/api/agent'],
    dependsOn: ['cards'],
    blueprint: '1.9',
    plan: [
      '多步 Agent：想一步、调一次工具、再想下一步',
      '技能：生成草稿 / 改写字段 / 体检 / 开场白 / 抽世界书 / 翻译 / 压缩',
      '创作辅助（3.2）：对话变成小说章节、角色卡一条龙出世界书 + 剧本、从对话抽取人物 / 地点 / 物品',
      'MCP 工具自动变成技能，与内置技能混在一起用',
      '每一步都可见：思考、调用、结果',
    ],
  },
  {
    id: 'cards',
    area: 'writing',
    title: '角色卡',
    summary: '导入导出、编辑、版本、收藏与标签',
    status: 'ready',
    nav: false,
    web: { view: 'cards', icon: '🃏' },
    api: ['/api/characters'],
    blueprint: '1.2',
    plan: [
      'PNG（chara / ccv3）与裸 JSON 卡的解析与写回',
      'V1 / V2 / V3 规格，未知字段无损往返',
      '字段编辑：名字、简介、性格、场景、开场白、示例、系统提示、后置指令',
      '批量导入文件夹、导出 PNG 卡',
      '搜索、收藏、自定义标签',
      '卡版本历史与回滚',
      '剧本大纲：一句话梗概 + 分章梗概（已实现，存在卡数据的 extensions 里）',
      '卡内 BGM / 音效清单：给卡绑一组音乐（已实现）',
      '角色关系图：亲疏 / 阵营 / 敌对关系可视化（已实现，纯 DOM 圆环图）',
      '一致性锁定：几个关键设定钉死，改稿时拒绝修改（已实现，界面 / Agent / MCP 都拦）',
    ],
  },
  {
    id: 'card-frontend',
    area: 'writing',
    title: '卡内前端与全局外观',
    summary: '卡自带 HTML/CSS/JS（沙箱），以及全局主题与布局',
    status: 'ready',
    nav: false,
    web: { view: 'card-frontend', icon: '🎨' },
    api: ['/api/frontend'],
    dependsOn: ['cards'],
    blueprint: '1.3',
    plan: [
      '卡内 HTML/CSS/JS 沙箱渲染（iframe sandbox=allow-scripts + 白名单 CSP，已实现）',
      '能力边界定死：越界写法静态校验拦下，桥只放行声明过的能力（已实现）',
      '脚本能力：读写对话 / 角色变量、读消息、发消息、回合事件（已实现）',
      '写卡区里的预览模式（已实现）',
      '全局主题：配色 / 圆角等 CSS 变量可改、可命名保存、可随时应用（已实现）',
      '卡内代码持久化：HTML / CSS / JS 按 scope 存下来，可载入 / 删除（已实现）',
      '代码存到卡上、跟着 PNG / JSON 导出走（已实现）',
      '对话页里跑卡自带的界面：自己的卡自动跑，导入的卡要你点一下、可"信任这张卡"（信任绑代码指纹，已实现）',
      '布局：单栏 / 双栏 / 窄屏自适应三选一，侧栏可拖宽、可收起来（已实现）',
      '高级用户自定义 CSS / JS（同样沙箱，已实现）',
    ],
  },
  {
    id: 'prompts',
    area: 'writing',
    title: '提示词',
    summary: '分层提示词、预设、宏、正则脚本、前后置词',
    status: 'ready',
    nav: false,
    web: { view: 'prompts', icon: '📝' },
    api: ['/api/prompts'],
    blueprint: '1.4 / 1.5',
    plan: [
      '分层结构：全局系统 → 角色系统 → 预设队列 → 注入 → 历史 → 前置词',
      '每段可设角色、插入位置、插入深度、启停',
      '宏：内置宏 + 自定义宏 + 条件块',
      '正则脚本：发送前 / 接收后 / 只改显示',
      '输出后处理完整正则链：全局 → 角色卡 → 预设，AI 输出先过一遍再解析状态块 / 存历史；只改显示的脚本结果放 displayContent（已实现）',
      '预设库：导入导出酒馆格式',
      '前置词（prefill）与后置词（suffix），按角色 / 按对话',
      '上下文预算表与裁剪策略',
    ],
  },
  {
    id: 'prompt-xray',
    area: 'writing',
    title: '提示词 X 光机',
    summary: '每轮真正发出去的提示词，可查可搜可展开',
    status: 'ready',
    nav: false,
    web: { view: 'xray', icon: '🔍' },
    api: ['/api/xray'],
    dependsOn: ['prompts'],
    blueprint: '1.4',
    plan: [
      '每轮存一份完整的 prompt 快照',
      '按段展开、搜索、看到每段 token 与来源',
      '被裁剪 / 被跳过的内容也要记录原因',
      '手动踢掉某一段再重发',
    ],
  },
  {
    id: 'worldbook',
    area: 'writing',
    title: '世界书',
    summary: '关键词 / 正则 / 语义三种触发，条目编辑与试触发',
    status: 'ready',
    nav: false,
    web: { view: 'worldbook', icon: '📚' },
    api: ['/api/worldbooks'],
    blueprint: '1.6',
    plan: [
      '两种存储形状互通（酒馆导出 / 卡内嵌），字段不丢',
      '关键词触发：主次关键词、四种逻辑、大小写与整词、扫描深度、常量',
      '正则触发：支持捕获组引用',
      '语义触发：向量判断相关性，逐条阈值（已实现；接 ports.embed 用余弦，没有嵌入就退化成零依赖词重叠）',
      '条目字段：优先级、位置、概率、粘性、冷却、延迟、分组权重、忽略预算',
      '试触发面板：输入一段话看激活了哪些条目、为什么',
      '整体预算与优先级裁剪',
    ],
  },
  {
    id: 'memory',
    area: 'writing',
    title: '记忆',
    summary: '小总结 / 大总结 / 结构化档案三层',
    status: 'partial',
    nav: false,
    web: { view: 'memory', icon: '🧠' },
    api: ['/api/memory'],
    dependsOn: ['prompts'],
    blueprint: '1.7',
    plan: [
      '小总结：滚动摘要，挂在它覆盖的消息区间上，可编辑可重算',
      '大总结：总结的总结，保留关系变化、设定、伏笔、未完成的事',
      '结构化档案：人物表 / 事件表 / 物品表 / 地点表',
      '记忆可见性：这轮用了哪几条、为什么，能手动踢',
      '时间线视图与记忆热度（已实现：热度 = 新鲜度 + 层权重 + 覆盖区间 + 钉住）',
      '时间线点一条跳到对应消息（已实现：跳到「对话」并滚动 + 高亮那一条）',
    ],
  },
  {
    id: 'vectors',
    area: 'writing',
    title: '数据库与向量化',
    summary: '四类内容的嵌入、混合检索、增量更新',
    status: 'partial',
    nav: false,
    web: { view: 'vectors', icon: '🧭' },
    api: ['/api/vectors'],
    blueprint: '1.8',
    plan: [
      '四类内容独立开关与权重：世界书 / 参考资料 / 历史对话 / 记忆',
      '混合检索：关键词 + 向量融合排序',
      '嵌入来源可选：跟随聊天模型 / 指定模型 / 本地模型',
      '增量更新与"待处理"计数',
      '重排序（已实现：零依赖确定性打分，覆盖率 + 整句命中）',
      '失效向量的自检与清理',
    ],
  },
  {
    id: 'card-tools',
    area: 'writing',
    title: '写卡工具链',
    summary: '生成卡、对话式改卡、体检、翻译、抓料',
    status: 'planned',
    nav: false,
    web: { view: 'card-tools', icon: '🛠️' },
    api: ['/api/card-tools'],
    dependsOn: ['cards', 'prompts'],
    blueprint: '1.9',
    plan: [
      '卡生成器：从想法 / 一张图 / 一段设定生成完整卡',
      '对话式改卡：说一句改一句，先看 diff 再写入',
      '卡体检：人设矛盾、称呼不一致、token 过长',
      '一键去 AI 味',
      '翻译卡与世界书（保留字段结构）',
      '从网页 / wiki 抓料生成设定与世界书',
    ],
  },

  // ---------- 玩卡区 ----------
  {
    id: 'chat',
    area: 'playing',
    title: '对话',
    summary: '流式输出、重新生成、继续、扮演、多标签',
    status: 'partial',
    web: { view: 'chat', icon: '💬' },
    api: ['/api/chats'],
    dependsOn: ['cards', 'prompts', 'worldbook', 'memory'],
    blueprint: '2.1',
    plan: [
      '流式输出与逐条重生成 / 编辑 / 插入 / 删除',
      '候选回复（swipes）：再来一版追加候选，◀ ▶ 来回翻（已实现）',
      '继续（不新增用户回合）与扮演（草稿进输入框）',
      '每条消息显示 token 数，整轮显示花费',
      '系统消息 / 隐藏消息开关',
      '多模型热切换、多标签并行',
      '全文搜索、酒馆 JSONL 导入导出',
      '一张卡多个对话：卡库 / 编辑器 / 对话页顶栏都看得到"这是《某卡》的第 N 个对话"，能就地继续 / 新建 / 改名 / 删除 / 导出（已实现）',
      '对话配置：提示词 / 前置词 / 后置词三样能按对话覆盖卡片级，留空 = 跟随卡片，界面上分得清"覆盖值 vs 继承值"（已实现）',
      '模块（Mod）七件套：提示词 / CSS / HTML+JS / 世界书条目 / 正则脚本 / 背景图，加上导入导出与「存为模块」（已实现）',
    ],
  },
  {
    id: 'group-chat',
    area: 'playing',
    title: '群聊',
    summary: '多角色同场，四种说话策略',
    status: 'partial',
    web: { view: 'group', icon: '👥' },
    dependsOn: ['chat'],
    blueprint: '2.2',
    plan: ['自然 / 列表 / 手动 / 混合四种策略', '活跃度权重与静音', '角色之间互相对话', '多角色提示词隔离', '自动模式'],
  },
  {
    id: 'scene-state',
    area: 'playing',
    title: '场景状态',
    summary: '变量、属性、任务、物品、骰子',
    status: 'partial',
    web: { view: 'state', icon: '📊' },
    dependsOn: ['chat'],
    blueprint: '2.3',
    plan: ['对话变量与角色变量（新增角色变量的界面入口已补）', '状态面板（属性 / 好感度 / 任务 / 物品 / 地点 / 时间）', 'AI 每轮输出结构化状态改动', '手动改状态', '骰子与检定', '状态快照与回滚'],
  },
  {
    id: 'narration',
    area: 'playing',
    title: '叙事控制',
    summary: '行动选项、分支存档、导演模式',
    status: 'partial',
    web: { view: 'narration', icon: '🎬' },
    dependsOn: ['chat'],
    blueprint: '2.4',
    plan: [
      '每轮 3-4 个候选行动按钮',
      '分支与存档',
      '导演模式（旁白身份插话定走向）',
      '局部重写与微调',
      '章节管理：把长对话切成章、可命名、可跳到那一条（已实现）',
      '结局收集：记录触发的结局，界面里看图鉴（已实现）',
      '随机事件：按概率插一条旁白小插曲，概率与事件清单可调（已实现）',
    ],
  },
  {
    id: 'performance',
    area: 'galgame',
    title: '演出层',
    summary: '立绘、背景、对话框、转场、导出 Ren\'Py',
    status: 'partial',
    web: { view: 'performance', icon: '🎭' },
    dependsOn: ['chat', 'imagegen'],
    api: ['/api/staging'],
    blueprint: '2.5',
    plan: [
      '背景层（已实现：场景状态的地点 + ComfyUI 出的背景图）',
      '立绘与表情差分（已实现：按出图记录挑最近的角色图）',
      '对话框 + 打字机 + 点击继续（已实现）',
      '选项分支浮层（已实现：复用叙事控制的候选行动）',
      '一键导出 Ren\'Py 工程（已实现：zip = script.rpy + options.rpy + 素材）',
      '转场：黑屏 / 闪白 / 震动 / 镜头平移，可设时长与"场景变化时自动播放"（已实现）',
      'BGM / 音效：音频进素材库、音量可调、按地点自动切 BGM、音效库点一下放一声（已实现；受浏览器自动播放限制，点一下即开始）',
      'CG 回廊：生成过 / 触发过的图按内容去重收进相册（已实现）',
      '好感度与路线：阈值解锁不同剧情线、多结局收集（已实现）',
      'Ren\'Py 导出带上 BGM（已实现）',
      '标准 gal 排版：底部整宽对话框 + 名字牌 + 右下角 ▽ + 快速菜单（回退 / 履历 / 跳过 / 自动 / 存档 / 快存 / 快读 / 设置 / 隐藏），选项走画面正中一列（已实现，排版对着 Ren\'Py 默认 GUI 抄）',
      '演出脚本：消息里写 [场景: 旧书馆] / [立绘: 阿狸 微笑 左] / [BGM: 雨夜] / [音效: 开门] / [CG: 初雪] / [转场: 黑屏 800] / [结局: 恋人线]，人写、AI 写、群聊几个 AI 一起写都认（已实现）',
      '演出时间线：一条消息按"旁白 / 台词"切拍逐句推进，可回退、可从履历跳到任意一句，指示行自动跳过（已实现）',
      '素材绑定：剧本里写名字，界面上把名字挂到 ComfyUI 出好的图 / 音频上，一部戏通用（已实现）',
      'CG 收藏：演到那一句才解锁，没解锁的只给剪影 + 已解锁进度（已实现）',
      '播放手感与存档：文字速度 / 自动间隔 / 跳过未读可调；9 个存档槽 + 快存，槽位带缩略图、场景与台词（已实现）',
      '键鼠手感：空格 / 回车 / 左键推进、滚轮上下回退前进、按住 Ctrl 快进、Esc 或右键开菜单、H 或中键隐藏界面（已实现）',
      '立绘演出：左 / 中 / 右站位 + 大 / 中 / 小（同一张图缩放演"靠近"）+ 出场动画；说话的人亮、其他人压暗（已实现）',
      'BGM 淡入淡出：切曲是 crossfade，[BGM: 停] 淡出（已实现）',
      '章节标题卡：[章节: 第一章 雪] 走一次黑底淡入淡出（已实现）',
      '路线锁定：[路线: 恋人线] 进这条线，其它线锁上并标明"被谁锁住"，也能手动放出来（已实现）',
      '界面配色统一到全局主题（浅色 / 深色 / 暖色主题都跟着走），只有舞台本身保留深色对话框（已实现）',
      '语音（2.6）留了接口位：[语音: …] 标记已经能认、不漏进台词，设置里写明了等模型接入层允许加 speech 适配器就能通（未接）',
    ],
  },
  {
    id: 'galgame-frontend',
    area: 'galgame',
    title: '自定义前端',
    summary: '贴你自己的 HTML / CSS / JS，权限全开，还带代码审查',
    status: 'ready',
    web: { view: 'galgame-frontend', icon: '🧩' },
    dependsOn: ['chat'],
    api: ['/api/galgame'],
    blueprint: '2.5',
    plan: [
      '一个入口：把你的 HTML / CSS / JS 贴进来，就能在沙箱里跑起来（已实现）',
      '权限全开：这是你一个人的板块 —— 跳过静态检查、沙箱能力全给、允许加载外链资源（已实现）',
      '代码审查：把 AI 写的代码先体检一遍，语法错、沙箱越界、常见坑逐条列出来（已实现）',
      'galgame 提示词：这个板块自带一套提示词，能一键套到某个对话上（已实现）',
    ],
  },
  {
    id: 'speech',
    area: 'galgame',
    title: '语音',
    summary: '朗读与语音输入，音色绑到角色',
    status: 'planned',
    web: { view: 'speech', icon: '🔊' },
    api: ['/api/speech'],
    blueprint: '2.6',
    plan: [
      'TTS 朗读新消息，音色按角色绑定（没做：要给 server/providers 加 speech 适配器，这次不允许动）',
      '语音输入（STT）（没做：同上，要 transcription 适配器）',
      '实时通话式对话、语音消息入历史（没做）',
    ],
  },
  {
    id: 'imagegen',
    area: 'playing',
    title: '图片生成',
    summary: '立绘、背景、CG，与剧情联动',
    status: 'partial',
    web: { view: 'imagegen', icon: '🖼️' },
    api: ['/api/images'],
    blueprint: '2.7',
    plan: [
      '立绘 / 背景 / CG 生成并自动入库（已实现，复用 ComfyUI 3.1，不另造一套）',
      '场景变化时自动出图（已实现：comfy 的 auto 触发）',
      '演出层里按当前场景出一张背景（已实现）',
      '局部重绘 / 扩图 / 图生图 / 表情差分批量 / 角色绑工作流与 LoRA（已实现，见 ComfyUI 接入）',
      '标签超市、以图搜图式素材管理（还没做）',
    ],
  },

  // ---------- 工具箱 ----------
  {
    id: 'comfyui',
    area: 'toolbox',
    title: 'ComfyUI 接入',
    summary: '导入工作流、占位符参数、队列进度',
    status: 'partial',
    web: { view: 'comfyui', icon: '🧩' },
    api: ['/api/comfy'],
    dependsOn: ['imagegen'],
    blueprint: '3.1',
    plan: [
      '填地址即可连接（本地 / 远程），连不上给出清楚原因（已实现）',
      '导入 API 格式工作流 JSON，自动标记可填参数（已实现）',
      '占位符 {{char}} {{scene}} {{emotion}} {{user}} 发请求前替换（已实现）',
      '三种触发：手动 / 标记触发 / 场景变化自动（已实现）',
      '结果自动入库（素材库）并与消息绑定（已实现）',
      '对话里直接看到出图缩略图、点开大图、进度与失败原因（已实现）',
      '队列与进度显示（WebSocket 进度 + 轮询收尾，已实现）',
      '内置立绘 / 表情差分 / 背景 / CG / 局部重绘 / 图生图 / 扩图 七种示例工作流，一键添加（已实现）',
      '两种执行方式：服务器执行 / 浏览器直连（client 模式下主机不向用户地址发请求，多用户模式默认 client；半自动 / 全自动触发在 client 模式下落成待办，前端在线时执行，已实现）',
      '种子固定、参数可调、绑定可加可删（已实现）',
      '批量表情差分：一次出开心 / 难过 / 生气 / 害羞等（已实现，两种执行方式都支持）',
      '图生图 / 局部重绘 / 扩图：参考图从素材库来，执行方自动上传给 ComfyUI（已实现）',
      '不同角色绑不同工作流 / LoRA 触发词，还带卡内表情差分包（按情绪自动换立绘，已实现）',
    ],
  },
  {
    id: 'cost',
    area: 'toolbox',
    title: '花费与统计',
    summary: 'token 与金额按对话 / 角色 / 天汇总',
    status: 'ready',
    web: { view: 'cost', icon: '💰' },
    api: ['/api/cost'],
    blueprint: '3.2',
    plan: [
      'usage 落库（每轮一条，消息删了统计还在）',
      '按对话 / 角色 / 天 / 模型 / 提供方汇总',
      '可填各家单价（价目表覆盖提供方自带的 priceIn / priceOut）；「+ 模型名」候选直接取你配好的提供方与绑定，不写死型号（已实现）',
      '预估与实际对比（提供方没报 usage 的轮次会标成"估算"）',
      '提示词缓存节省统计（适配层把各家的缓存命中字段透传成 cachedTokens）',
    ],
  },
  {
    id: 'mcp',
    area: 'toolbox',
    title: 'MCP 服务器',
    summary: '让 Codex / Claude Code 直接读写酒馆',
    status: 'ready',
    web: { view: 'mcp', icon: '🔌' },
    api: ['/api/mcp'],
    blueprint: '3.2',
    plan: [
      'stdio 传输（server/mcp-stdio.mjs），零依赖',
      '列角色 / 查对话 / 发消息触发回复 / 改世界书 / 切预设 / 看提示词快照',
      '摘要 / 搜索 / 索引三种返回模式以省 token',
      '破坏性操作二次确认（confirm: true）',
      '客户端方向照旧：外部 MCP 工具当写卡技能用',
    ],
  },
  {
    id: 'review',
    area: 'toolbox',
    title: '月度与年度报告',
    summary: '这个月玩了几张卡、写了几张卡、花了多少 token、最爱是谁',
    status: 'ready',
    web: { view: 'review', icon: '🗓️' },
    api: ['/api/review'],
    dependsOn: ['cost'],
    blueprint: '3.2',
    plan: [
      '月报 / 年报 / 全部时间三档，可切月份与年份',
      '花费与产量：轮数、输入输出 token、花费、缓存节省、Top 10 卡与 Top 模型',
      '陪伴与活跃：活跃天数、最长连续、峰值日、时段与星期分布（按本地时区）',
      '产出与创作：你写了多少字、新卡 / 改卡、世界书 / 预设 / 记忆、出图数',
      '一句话总结（本地拼，不花 token）',
    ],
  },
  {
    id: 'backup',
    area: 'toolbox',
    title: '备份与维护',
    summary: '快照、恢复、数据清理与统计',
    status: 'ready',
    web: { view: 'backup', icon: '🧰' },
    api: ['/api/maintenance'],
    blueprint: '3.2',
    plan: [
      '一键全量备份 / 恢复（VACUUM INTO 快照 + 素材，打成一个 zip）',
      '自动备份（每次启动、恢复前、清理前），保留最近 N 份',
      '清理孤立素材 / 缺文件的记录 / 失效向量 / 重复消息 / 空对话',
      '数据统计（角色、对话、消息、字数、素材占用……）',
      '恢复不用重启：把备份里的表整体搬回正在用的库，字段对不上会明确拒绝',
    ],
  },
  {
    id: 'scheduler',
    area: 'toolbox',
    title: '定时任务',
    summary: '每天 / 每周自动备份、清理、写总结',
    status: 'ready',
    web: { view: 'scheduler', icon: '⏰' },
    api: ['/api/scheduler'],
    dependsOn: ['backup', 'memory'],
    blueprint: '3.2',
    plan: [
      '零依赖调度器（setInterval + app_meta 落库"上次跑的时间"），重启不重复跑、错过补一次（已实现）',
      '每天 / 每周的某个时刻；三种动作：备份 / 清理 / 给定对话写小总结或大总结（已实现）',
      '界面开关 + 上次 / 下次运行时间 + "立刻跑一遍"（已实现）',
    ],
  },

  // ---------- 平台 ----------
  {
    id: 'providers',
    area: 'platform',
    title: '模型接入',
    summary: '聊天 / 嵌入 / 图片 / 语音提供方',
    status: 'partial',
    web: { view: 'providers', icon: '🔗' },
    api: ['/api/providers'],
    blueprint: '3',
    plan: [
      '提供方注册表与能力声明（已实现）',
      '密钥加密存储、连通性测试、查询可用模型（已实现）',
      '模型分工（多模型协同）：一张"谁用哪个模型"的表，按 群聊成员 > 角色 > 对话 > 全局默认 生效；每行就地选提供方 + 模型（模型名可搜、可从服务商拉），改动立刻落库，不用点保存（已实现）',
      '分工预览：选一个群聊就让服务端按**真实成员**算一遍，所以"群聊成员覆盖"也能算对；没选群聊就按所有角色卡算（已实现）',
      '参数覆盖：需要给某一行单独调采样参数时，用行末的 ⚙ 写 JSON（已实现）',
    ],
  },
  {
    id: 'assets',
    area: 'platform',
    title: '素材库',
    summary: '图片、音频等文件的统一存储',
    status: 'partial',
    web: { view: 'assets', icon: '🗂️' },
    api: ['/api/assets'],
    plan: [
      '按内容哈希去重存储（已实现）',
      '与消息关联（ComfyUI 出的图会挂到那条回复上，已实现）',
      '上传 / 列表 / 取字节 / 删除（已实现）',
      '素材库页面：网格预览、按类型筛选、上传 / 删除（已实现）',
      '引用计数：消息 / 出图记录 / 角色头像各引用了几次，删之前能看到（已实现）',
      '缩略图（还没做：现在直接用原图当缩略图，靠 CSS 缩小）',
    ],
  },
  {
    id: 'settings',
    area: 'platform',
    title: '设置',
    summary: '界面、数据、日志等全局设置',
    status: 'partial',
    web: { view: 'settings', icon: '⚙️' },
    api: ['/api/settings'],
    blueprint: '3.2',
    plan: [
      '设置项 schema 与校验（已实现）',
      '界面设置：主题（含护眼暖色）/ 语言 / 密度 / 强调色（已实现）',
      '快捷键自定义（发送 / 继续 / 重生成 / 切换角色 / 搜索，已实现）',
      '生成完成通知：响一下 + 浏览器通知（已实现）',
      '数据目录与迁移（待补）',
    ],
  },
  {
    id: 'data',
    area: 'platform',
    title: '数据与迁移',
    summary: '数据库 schema、版本化迁移、导入导出',
    status: 'stub',
    web: { view: 'data', icon: '🧱' },
    api: ['/api/data'],
    plan: ['版本化迁移（已实现）', '整体导出 / 导入', '数据完整性自检'],
  },
  {
    id: 'plugins',
    area: 'platform',
    title: '插件机制',
    summary: 'data/plugins/<名字>/ 放插件即可加载（视图 / 接口 / 技能 / 工具）',
    status: 'ready',
    nav: false,
    web: { view: 'plugins', icon: '🔌' },
    api: ['/api/plugins'],
    dependsOn: ['settings'],
    blueprint: '3.2',
    plan: [
      'plugin.json 清单 + index.mjs 入口，目录放对就加载（已实现）',
      '四种钩子：注册 HTTP 接口 / 写卡技能 / MCP 工具 / 界面视图（已实现）',
      '插件视图由 /api/plugins/<名字>/<文件> 提供，纯 ESM 无构建（已实现）',
      '单个插件坏了只记警告，不影响主服务启动（已实现）',
    ],
  },
  {
    id: 'multi-user',
    area: 'platform',
    title: '多用户（给朋友用）',
    summary: '一个网址 + 登录，每人一个数据目录，互相看不见',
    status: 'ready',
    nav: false,
    web: { view: 'host', icon: '🛡️' },
    api: ['/api/auth', '/api/host'],
    dependsOn: ['settings'],
    blueprint: '3.2',
    plan: [
      '账号表 + scrypt 口令 + 内存会话（已实现，重启全员重新登录）',
      '一个账号 = 一个完整数据目录，按会话把请求交给对应租户的 app（已实现）',
      '主机管理：开账号 / 停用 / 重置口令 / 删除 / 卸载租户 / 磁盘占用（已实现）',
      '加密导出（.stbk，AES-256-GCM + scrypt 口令）：主机管理员也解不开（已实现）',
      '登录失败按 IP 限速；HTTPS 下自动 Secure Cookie（已实现）',
      '成员不能"让主机替他做事"：本地代理托管、本地 MCP 服务器、ComfyUI 主机代连都只有管理员能用（已实现）',
      '端到端用例 + 37 条手动清单全绿；安全边界与已知取舍见 docs/SECURITY.md（已实现）',
    ],
  },
];
